name: Build Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Build and publish docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docs/docfx.json

      - name: Publish documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          force_orphan: true
